# Generated by Django 2.2.6 on 2019-11-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0004_auto_20191115_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='age_18to24_population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_18to24_registered_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_18to24_registered_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_18to24_voted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_18to24_voted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_25to34_population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_25to34_registered_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_25to34_registered_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_25to34_voted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_35to44_population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_35to44_registered_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_35to44_registered_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_35to44_voted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_35to44_voted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_45to64_population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_45to64_registered_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_45to64_registered_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_45to64_voted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_45to64_voted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_65plus_population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_65plus_registered_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_65plus_registered_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_65plus_voted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='age_65plus_voted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='asian_population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='asian_registered_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='asian_registered_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='asian_voted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='asian_voted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='black_population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='black_registered_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='black_registered_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='black_voted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='black_voted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='females_population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='females_registered_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='females_registered_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='females_voted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='females_voted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='hispanic_population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='hispanic_registered_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='hispanic_registered_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='hispanic_voted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='hispanic_voted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='males_population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='males_registered_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='males_registered_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='males_voted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='males_voted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='registered_voters_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='registered_voters_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='total_voters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='total_voters_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='white_population_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='white_registered_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='white_registered_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='white_voted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='white_voted_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
