# Generated by Django 2.2.6 on 2019-11-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0007_auto_20191116_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='term_end',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='term_start',
        ),
    ]
