# Generated by Django 2.2.6 on 2019-11-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0008_auto_20191119_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='next_election',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
